version: '3.4'

services:
    SalarySqlDb:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Password123"
        ports:
            - "11433:1433"
    SalaryApp:
        image: ${DOCKER_REGISTRY-}salaryapp
        build:
            context: .
            dockerfile: SalaryApp/Dockerfile
        ports: 
            - "8000:80"
